print("buongiorno prof")
a = int(input("Dammi un numero"))
print("Il doppio del tuo numero è" + a*2)
print("Il triplo è" + a*3)
print("La met�à è"  a/2)
print("Il quadrato è" + a*a)
n = int(input("dimmi il tuo numero preferito"))
print("Scommeto che è il tuo numero preferito percheè è il giorno del tuo compleanno")
print("speriamo nel 6 politico")
print("scusi prof non sapevo cosa scrivere")
